[package]
name = "static_cell"
version = "1.0.0-alpha.1"
edition = "2021"
description = "Statically allocated, initialized at runtime cell."
license = "MIT OR Apache-2.0"
repository = "https://github.com/embassy-rs/static-cell"

[dependencies]
atomic-polyfill = "1.0.1"
